version: "3.8"

services:
  server:
    image: arya51090/myapp-server:latest
    container_name: myapp-server
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production

  frontend:
    image: arya51090/myapp-frontend:latest
    container_name: myapp-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: http://server:5000
    depends_on:
      - server
